# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-BigBrother
version:      0.10
version_from: lib/POE/Filter/BigBrother.pm
installdirs:  site
requires:
    POE:                           0.38

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
